GET http://localhost:8000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZGluYSIsImlhdCI6MTY1NTY5OTY1OX0.P_80eV-N_xgCwCokrNqkHBH4r7byfafqoJ_EmJmleqI

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "dina"
}

###
POST  http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZGluYSIsImlhdCI6MTY1NTY5OTY1OX0.P_80eV-N_xgCwCokrNqkHBH4r7byfafqoJ_EmJmleqI"
}

